### ISSUE TITLE
LSTM + Stitch

### ISSUE THREAD

**Issue by xiaoxutongxu** [maria-korosteleva/Garment-Pattern-Estimation#10]
Sorry for me to ask, I ran this line of code and got the following error, what's going on?
I think it runs by predicting first, and then making other predictions on the data it predicts?

code:python nn/evaluation_scripts/on_test_set.py -st models/baseline/lstm_stitch_tags.yaml
error:
Traceback (most recent call last):
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/evaluation_scripts/on_test_set.py", line 103, in <module>
    stitch_dataset, stitch_datawrapper = stitch_experiment.load_dataset(in_datapath, unseen=args.unseen, batch_size=1, load_all=True)  # Num of edge pairs at test time is different for each sewing pattern 
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/experiment.py", line 222, in load_dataset
    dataset = data_class(data_root, data_config, gt_caching=True, feature_caching=True)
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/data/datasets.py", line 586, in __init__
    super().__init__(root_dir, start_config, 
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/data/datasets.py", line 367, in __init__
    super().__init__(root_dir, start_config, gt_caching=gt_caching, feature_caching=feature_caching, in_transforms=in_transforms)
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/data/datasets.py", line 83, in __init__
    self._estimate_data_shape()
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/data/datasets.py", line 331, in _estimate_data_shape
    elem = self[0]
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/data/datasets.py", line 110, in __getitem__
    features, ground_truth = self._get_sample_info(datapoint_name)
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/data/datasets.py", line 784, in _get_sample_info
    points, verts = self._sample_points(datapoint_name, folder_elements)
  File "/root/autodl-tmp/Garment-Pattern-Estimation-master/nn/data/datasets.py", line 833, in _sample_points
    raise RuntimeError('Dataset:Error: geometry file *{}*.obj not found for {}'.format(self.config['obj_filetag'], dat

**Comment by maria-korosteleva** [comment]
Hi! Thank you for your interest in our work :)

Indeed, by default it starts by predicting panel shapes from a geometry,
but as error indicates, it fails to find the geometry files in the data
that you supply. Please, check the test data that you provide

If you want to run stitch prediction on the existing sewing patterns, it's
possible to do as well. Check the command arguments here, second to last
example in this section of the docs:
https://github.com/maria-korosteleva/Garment-Pattern-Estimation/blob/master/docs/Running.md#examples-of-evaluation-commands


Let me know if this works for you!
